---
- name: Add PPA for new versions of Git
  sudo: yes
  apt_repository: repo='ppa:git-core/ppa' state=present
- name: Update and upgrading packages
  sudo: yes
  apt: update_cache=yes upgrade=safe
- name: Install software-properties-common
  sudo: yes
  apt: pkg=software-properties-common state=latest
- name: Install python-setuptools
  sudo: yes
  apt: pkg=python-setuptools state=latest
- name: Install pip3
  sudo: yes
  apt: pkg=python3-pip state=latest
- name: Install python3-setuptools
  sudo: yes
  apt: pkg=python3-setuptools state=latest
- name: Install pip again with easyintall
  sudo: yes
  command: python3 -m easy_install pip
- name: Install git
  sudo: yes
  apt: pkg=git state=latest
- name: Clone rep from BitBucket
  git: accept_hostkey=true repo="{{ project_git_url }}" dest="~/{{ name_project }}"
- name: Ensure supervisor is up to date
  sudo: yes
  apt: pkg=supervisor state=latest
- name: Ensure geniusfeed stop
  sudo: yes
  supervisorctl: name={{ name_project }} state=stopped
- name: set the locale
  sudo: yes
  shell: "export LANG=en_US.UTF-8"
- name: set the locale
  sudo: yes
  shell: "echo 'LANGUAGE=\"en_US.UTF-8\"' >> /etc/default/locale"
- name: set the locale
  sudo: yes
  shell: "echo 'LC_ALL=\"en_US.UTF-8\"' >> /etc/default/locale"
- name: set the locale
  sudo: yes
  shell: "locale-gen 'en_US.UTF-8'"
- name: set the locale
  sudo: yes
  shell: "dpkg-reconfigure locales"