---
- name: install and update postgresql dependencies
  sudo: yes
  apt: pkg=libpq-dev state=latest
- name: install and update python-dev
  sudo: yes
  apt: pkg=python-dev state=latest
- name: Build dependencies for python-psycopg2
  sudo: yes
  apt: pkg=python-psycopg2 state=build-dep
- name: instal python-psycopg2
  sudo: yes
  apt: pkg=python-psycopg2 state=latest
- name: Install postgresql
  sudo: yes
  apt: pkg=postgresql state=latest
  notify: restart postgresql
- name: Install libpq-dev
  sudo: yes
  apt: pkg=libpq-dev state=latest
- name: PostgreSQL contrib
  sudo: yes
  apt: pkg=postgresql-contrib state=latest
- name: ensure the postgreSQL service is running
  sudo: yes
  service: name=postgresql state=started enabled=yes
- name: create db
  postgresql_db: name="{{ db_name }}"
  sudo: yes
  sudo_user: postgres
- name: create postgresql user and grant access to db
  postgresql_user: db="{{ db_name }}" name="{{ db_user }}" password="{{ db_pass }}"
  sudo: yes
  sudo_user: postgres